### ISSUE TITLE
[BUG] there is some typo error 

### ISSUE THREAD

**Issue by sumanttyagi** [LADI-Dataset/ladi-overview#15]
- [ ]  1 on hugging face everywhere you have written v2 dataset , as per the git readme the model is trained on v2a ?https://github.com/LADI-Dataset/ladi-overview/issues even in github but the classes of v2a is mentioned as per technical write up .
![image](https://github.com/user-attachments/assets/70957886-3300-4d01-b98c-ca9359d92983)

Please give us clarity - or update the documentation

- [ ]  2 - Also did you  used the resized version (i.e. resized version was used for training ) for publishing the model  or just the v2a dataset for training model ? 
- [ ] 3 If the raw images were of varied sizes, how did you choose the final dimensions? Did you use any sampling methods? If so, to what scale? I noticed that the input size of the images is 448x448. for LADI-v2-classifier-small
- [ ] 4  - reference model reference model , Could you please provide more details on how the results of this paper differ from those of other models? Specifically, how did using 80% of the images impact the outcomes? Why did you choose not to train the model with the entire dataset? Additionally, can you provide any use cases for this approach publishing the reference model ? (i.e please share more details how paper results is different from other model ? using 80 % images how did it helped why did not just train model with all dataset why reference any use case to it ?)

**Comment by sscheele** [comment]
Hi Sumant - question 1 is answered in the README. Since that's something like the fourth question you've asked that's answered in the README, I'd like to gently ask you to make sure you've read it before asking any more questions. If you're not a native English speaker and find that difficult, you might ask an LLM to read it for you and answer your questions.

As you point out, further resizing the images is done internally in the code, so it shouldn't really matter whether we used the resized versions or not, but we did use the resized versions for most of our runs. Input sizes were determined by the base model.

We did train the models which are not labeled as 'reference' on the entire dataset. The other questions you're asking in your point 4 relate to the basics of why we use train and test splits - I would encourage you to find the answers by taking an ML course or asking an LLM.

I really do appreciate your interest in our work, but to save myself some time I will close any further issues you open with questions you could answer with an LLM.
