### ISSUE TITLE
[BUG] asking LLM and getting few doubts 

### ISSUE THREAD

**Issue by sumanttyagi** [LADI-Dataset/ladi-overview#16]
On model card page: https://huggingface.co/MITLL/LADI-v2-classifier-large
![image](https://github.com/user-attachments/assets/7eaefa9e-daba-4044-9792-cbb0f189f7a2)
 i asked LLM as mentioned by  @sscheele 
![image](https://github.com/user-attachments/assets/37dae181-65dd-41ce-9618-1eda8d1ac616)

 can you please defend why you did so ? without any concrete proof and running it on 40k images you conclude that
![image](https://github.com/user-attachments/assets/c7f7178d-8972-456b-beef-99164c188dcb)
![image](https://github.com/user-attachments/assets/259dc7ea-61fc-4884-8095-2dfa9b8c65f0)
how this column of validation was generated if all splits where used ? it means your model has seen all you data 

![image](https://github.com/user-attachments/assets/eabfa7e4-6921-4d0b-8b81-453caf57b861)
 did you maintained above practice for validation @jeffliu-LL  are these team used three guys each to see images or it was just reviewed by ML expert like @sscheele who ask every question to LLM

**Comment by jeffliu-LL** [comment]
Sorry for the confusion, and I'm glad I was able to clarify. 

Note that in Section 4.1 we mention that the classifiers are named "LADI-v2-classifier-small-reference" and "LADI-v2-classifier-large-reference", but we refer to them as "small" and "large" for brevity.
![image](https://github.com/user-attachments/assets/7f329ca8-b991-4efe-a65e-506720349f80)

**Comment by jeffliu-LL** [comment]
Yes, all images were first resized to fit within 1800 x 1200 using bicubic resampling, maintaining original aspect ratio. For validation and test, we resize to fit the smaller dimension within the model's resolution, and then center crop to get the correct aspect ratio. This is a relatively standard pattern, but could lead to missed detections on the edges. You could modify it with padding to preserve aspect ratio if you desire, and it would be interesting to see if it results in better performance.

We provide the original resolution data if you would like to perform experiments on the high resolution images.

**Comment by jeffliu-LL** [comment]
The entire dataset was first resized to fit within 1800x1200 to speed up the training process, then fed to model which was resized so that the smaller dimension fit within model dimensions, preserving aspect ratio, and then center cropped to fit within the square. In your given example, we used method 1, followed by a center crop of the 672x448 to 448x448.

As you mentioned, this could potentially lead to missed detections from cropping out the edges. You may be able to achieve better performance with the same classifiers by using a different strategy for resizing, and we encourage you to experiment. The classifiers and information in the writeup are meant provide reasonable baselines using standard techniques.

**Comment by jeffliu-LL** [comment]
During training we use random resize crop from [albumentations](https://albumentations.ai/) for augmentation. Yes, that is a possible edge case during training and is a potential area for additional optimization. You should be able to see the settings we use if you look in the training code - we did not do an ablation study on the settings for the data augmentations, so we do not know to what degree this affected the performance. If this is something you are interested in, we encourage you to perform experiments on it.
